--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: eugine
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO eugine;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: escrow_transactions; Type: TABLE; Schema: public; Owner: eugine
--

CREATE TABLE public.escrow_transactions (
    id bigint NOT NULL,
    amount numeric(38,2),
    buyer_email character varying(255),
    checkout_request_id character varying(255),
    completed_at timestamp(6) without time zone,
    failure_reason character varying(255),
    initiated_at timestamp(6) without time zone,
    merchant_request_id character varying(255),
    mpesa_receipt_number character varying(255),
    payment_type character varying(255),
    phone_number character varying(255),
    property_id bigint,
    status character varying(255),
    CONSTRAINT escrow_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'IN_ESCROW'::character varying, 'RELEASED'::character varying, 'REFUNDED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.escrow_transactions OWNER TO eugine;

--
-- Name: escrow_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: eugine
--

ALTER TABLE public.escrow_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escrow_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: eugine
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    email character varying(255),
    expires_at timestamp(6) without time zone,
    token character varying(255),
    used boolean NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO eugine;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: eugine
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties; Type: TABLE; Schema: public; Owner: eugine
--

CREATE TABLE public.properties (
    id bigint NOT NULL,
    ardhisasa_verified boolean NOT NULL,
    description text,
    image_url character varying(255),
    location character varying(255),
    price numeric(38,2),
    title character varying(255),
    type character varying(255),
    owner_id bigint
);


ALTER TABLE public.properties OWNER TO eugine;

--
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: eugine
--

ALTER TABLE public.properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: eugine
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255),
    enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['BUYER'::character varying, 'SELLER'::character varying, 'AGENT'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO eugine;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: eugine
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: escrow_transactions; Type: TABLE DATA; Schema: public; Owner: eugine
--

COPY public.escrow_transactions (id, amount, buyer_email, checkout_request_id, completed_at, failure_reason, initiated_at, merchant_request_id, mpesa_receipt_number, payment_type, phone_number, property_id, status) FROM stdin;
1	45000000.00	kellyeugine583@gmail.com	ws_CO_24042026230314113708374149	\N	\N	2026-04-24 23:03:14.405128	685a-4af3-a44f-a3c82dae3d0c33444	\N	STK_PUSH	254708374149	2	PENDING
2	1500.00	kellyeugine583@gmail.com	ws_CO_25042026161532055708374149	\N	\N	2026-04-25 16:15:32.399186	d930-4248-becf-279e7043e76814564	\N	STK_PUSH	254708374149	2	PENDING
3	1500.00	kellyeugine583@gmail.com	ws_CO_25042026165534189708374149	\N	\N	2026-04-25 16:55:34.608731	685a-4af3-a44f-a3c82dae3d0c66944	\N	STK_PUSH	254708374149	2	PENDING
4	1500.00	kellyeugine583@gmail.com	ws_CO_25042026165702181708374149	\N	\N	2026-04-25 16:57:02.566548	d930-4248-becf-279e7043e76815911	\N	STK_PUSH	254708374149	2	PENDING
5	1000.00	kellyeugine583@gmail.com	ws_CO_29042026113952878708374149	\N	\N	2026-04-29 11:39:53.31974	d707-4878-9d26-6e80d84d20e044412	\N	STK_PUSH	254708374149	1	PENDING
6	1500.00	kellyeugine583@gmail.com	ws_CO_29042026220103007708374149	\N	\N	2026-04-29 22:01:03.299997	98af-41cc-b897-7b9aa487500968631	\N	STK_PUSH	254708374149	2	PENDING
7	1500.00	kellyeugine583@gmail.com	ws_CO_30042026145657465708374149	\N	\N	2026-04-30 14:56:57.993685	08e6-4ff8-a042-c46dbbe741bf66962	\N	STK_PUSH	254708374149	2	PENDING
8	1500.00	kellyeugine583@gmail.com	ws_CO_04052026120116300708374149	\N	\N	2026-05-04 12:01:16.907914	0a9b-4232-a515-ad2a1bd93c1316974	\N	STK_PUSH	254708374149	2	PENDING
9	1000.00	kellyeugine583@gmail.com	ws_CO_06052026112522017708374149	\N	\N	2026-05-06 11:25:22.514255	c82a-4779-9271-e3981394faed303	\N	STK_PUSH	254708374149	1	PENDING
10	1000.00	kellyeugine583@gmail.com	ws_CO_06052026172149817708374149	2026-05-11 15:11:19.021895	\N	2026-05-06 17:21:50.109117	8fea-4eba-8a22-2660103df01928995	LGR12345TEST	STK_PUSH	254708374149	1	IN_ESCROW
11	1000.00	kellyeugine583@gmail.com	ws_CO_11052026151410159708374149	\N	\N	2026-05-11 15:14:10.491392	e9d4-4e35-99d1-3876a8cbbc4029915	\N	STK_PUSH	254708374149	1	PENDING
12	1000.00	kellyeugine583@gmail.com	ws_CO_11052026205005995708374149	\N	\N	2026-05-11 20:50:06.411272	fa8c-47b5-a1d7-ebaebbc78c292111	\N	STK_PUSH	254708374149	3	PENDING
13	1500.00	kellyeugine583@gmail.com	ws_CO_30052026112157346708374149	2026-05-30 11:22:00.841935	\N	2026-05-30 11:21:57.696759	5c90-402a-bdc0-51ad014a4dda17444	SANDBOX1780129320743	STK_PUSH	254708374149	2	IN_ESCROW
14	1500.00	kellyeugine583@gmail.com	ws_CO_30052026112215246708374149	2026-05-30 11:22:24.018553	\N	2026-05-30 11:22:15.557696	5c90-402a-bdc0-51ad014a4dda17460	SANDBOX1780129343970	STK_PUSH	254708374149	2	IN_ESCROW
15	1500.00	kellyeugine583@gmail.com	ws_CO_30052026112325743708374149	2026-05-30 11:23:35.908747	\N	2026-05-30 11:23:26.059487	a09d-4e35-9559-b4c85f643ac814908	SANDBOX1780129415871	STK_PUSH	254708374149	2	IN_ESCROW
16	1500.00	kellyeugine583@gmail.com	ws_CO_30052026112345865708374149	2026-05-30 11:23:53.444121	\N	2026-05-30 11:23:46.24124	a09d-4e35-9559-b4c85f643ac814917	SANDBOX1780129433396	STK_PUSH	254708374149	2	IN_ESCROW
25	200.00	kellyeugine583@gmail.com	ws_CO_16062026203933841708374149	2026-06-16 20:39:35.964238	\N	2026-06-16 20:39:34.130805	9584-46ca-a080-d42019dd6c9e53239	SANDBOX1781631575933	STK_PUSH	254708374149	102	IN_ESCROW
19	200.00	kellyeugine583@gmail.com	ws_CO_31052026135158598741505192	2026-05-31 13:52:01.814458	No response from user.	2026-05-31 13:51:59.038752	0a22-4595-a382-d1a95189817f15776	SANDBOX1780224721736	STK_PUSH	254741505192	102	FAILED
18	1000.00	kellyeugine583@gmail.com	ws_CO_30052026195227141708374149	2026-05-30 19:52:29.731211	DS timeout user cannot be reached.	2026-05-30 19:52:27.506139	a09d-4e35-9559-b4c85f643ac837985	SANDBOX1780159949691	STK_PUSH	254708374149	1	IN_ESCROW
26	200.00	kellyeugine583@gmail.com	ws_CO_17062026120158288708374149	2026-06-17 12:02:00.858463	\N	2026-06-17 12:01:58.606216	eb45-43b3-a3d4-218ee9f921eb6326	SANDBOX1781686920806	STK_PUSH	254708374149	101	IN_ESCROW
20	200.00	kellyeugine583@gmail.com	ws_CO_31052026135235664708374149	2026-05-31 13:52:38.549369	DS timeout user cannot be reached.	2026-05-31 13:52:36.751723	30ff-4d2b-b54b-9e6f0ab740fe31506	SANDBOX1780224758506	STK_PUSH	254708374149	102	IN_ESCROW
21	500.00	kellyeugine583@gmail.com	ws_CO_31052026135305481741505192	2026-05-31 13:53:11.569917	No response from user.	2026-05-31 13:53:06.781864	30ff-4d2b-b54b-9e6f0ab740fe31526	SANDBOX1780224791531	STK_PUSH	254741505192	4	FAILED
17	1000.00	kellyeugine583@gmail.com	ws_CO_30052026195208036708374149	2026-05-30 19:52:10.682189	DS timeout user cannot be reached.	2026-05-30 19:52:08.462159	a09d-4e35-9559-b4c85f643ac837968	SANDBOX1780159930610	STK_PUSH	254708374149	1	REFUNDED
22	200.00	kellyeugine583@gmail.com	ws_CO_01062026115438783708374149	\N	DS timeout user cannot be reached.	2026-06-01 11:54:39.073425	4413-468c-b949-a0f46ce25243914	\N	STK_PUSH	254708374149	102	FAILED
23	1000.00	kellyeugine583@gmail.com	ws_CO_09062026153131114708374149	2026-06-09 15:31:36.304478	\N	2026-06-09 15:31:31.65345	c5a4-4eca-82c9-fa8306549c6a126169	SANDBOX1781008296196	STK_PUSH	254708374149	3	IN_ESCROW
24	1000.00	kellyeugine583@gmail.com	ws_CO_16062026170844600708374149	2026-06-16 17:08:47.740239	\N	2026-06-16 17:08:44.868626	9584-46ca-a080-d42019dd6c9e42377	SANDBOX1781618927666	STK_PUSH	254708374149	8	IN_ESCROW
\.


--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: eugine
--

COPY public.password_reset_tokens (id, email, expires_at, token, used) FROM stdin;
2	kellyeugine583@gmail.com	2026-06-16 15:38:17.690816	32584b22-e8b5-48de-8164-743916df9c10	t
\.


--
-- Data for Name: properties; Type: TABLE DATA; Schema: public; Owner: eugine
--

COPY public.properties (id, ardhisasa_verified, description, image_url, location, price, title, type, owner_id) FROM stdin;
1	t	Modern apartment with stunning city views and 24/7 security.	https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=600	Westlands, Nairobi	12500000.00	3 Bedroom Apartment	Apartment	1
2	t	Spacious family home with large garden and swimming pool.	https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600	Karen, Nairobi	45000000.00	4 Bedroom Villa	House	1
4	t	Cozy apartment in a prime location near amenities.	https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=600	Kilimani, Nairobi	8900000.00	2 Bedroom Apartment	Apartment	1
3	t	Prime commercial land suitable for development.	https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=600	Mombasa Island	28000000.00	Commercial Plot	Land	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: eugine
--

COPY public.users (id, email, full_name, password, phone, role, enabled) FROM stdin;
2	tneugine@gmail.com	Otieno	$2a$12$fI7cjT2dzkGvOnUC6HxQsuh4aiQfymILatHHdSRDCnxTmGtw7R9KW	0741505192	BUYER	t
3	okongoeugine84@gmail.com	okongo eugine	$2a$12$VijnNBBCuGxB2dAatbR3t.FAi/bXIE7e52FnOxIqU9m3X.6T3FYS6	\N	BUYER	t
4	marknjoroge@gmail.com	Mark Njoroge	$2a$12$t58MkckBQXZXN1p./7pIIeYReOsY1ulZEcVRN/TRL7bOdpjzD.Okm	0720085033	BUYER	t
1	kellyeugine583@gmail.com	Eugine Kelly Otieno	$2a$12$5Smsz.QUKnUU19LqRS9CW.zBN0Te3hcSaYZCkZuIlyytZTFRtoVoe	0741505192	ADMIN	t
5	markkelly@gmail.com	Mark Kelly	$2a$12$3AC2nQ7JnGIdFkm/X9g/9..Cs218b2dnJGglnzvUg2PPv/KDr2ICa	0710853942	BUYER	t
6	mathew@gmail.com	Eugine Mathews	$2a$12$dBB7iSkYrFbAFc7mg5qRd.7xMms1C7pqZQq7M9VlVxYrREtrYvzlO	07209813y	BUYER	t
\.


--
-- Name: escrow_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eugine
--

SELECT pg_catalog.setval('public.escrow_transactions_id_seq', 26, true);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eugine
--

SELECT pg_catalog.setval('public.password_reset_tokens_id_seq', 2, true);


--
-- Name: properties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eugine
--

SELECT pg_catalog.setval('public.properties_id_seq', 6, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: eugine
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: escrow_transactions escrow_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: eugine
--

ALTER TABLE ONLY public.escrow_transactions
    ADD CONSTRAINT escrow_transactions_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: eugine
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: eugine
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: eugine
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: eugine
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: properties fk32k2h9s30s0ukftb8hj947ef2; Type: FK CONSTRAINT; Schema: public; Owner: eugine
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT fk32k2h9s30s0ukftb8hj947ef2 FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

